### ISSUE TITLE
BUG: SELECT current_date; -> value function (1) is not allowed

### ISSUE THREAD

**Issue by emarsden** [xataio/feedback#14]
Hi,

```
> select current_date;
value function (1) is not allowed     (expecting "2024-07-29")
```

This is with xata which reports itself as "PostgreSQL 15.5" (current free plan version). It would be useful for users if the server_version string included Xata, to help identify the PostgreSQL variant used (most other modified PostgreSQL implementations include something like this).

**Comment by amvieites** [comment]
Hello Eric, thanks for the report.
We have a PR up waiting for tests and review that will solve the issue today.
As for your suggestion regarding versioning, we did discuss this differentiation at an early stage but discarded it; I'll raise your feedback internally in order to review that decision.

Hope this helps, and thank you again.
